cloud:
  aws:
    credentials:
      access-key: AKIA3YMNLFDV4CTETHDN
      secret-key: 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
    region:
      static: sa-east-1
    stack:
      auto: false

application:
  bucket:
    name: barganhaleilao


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090