cloud:
  aws:
    credentials:
      access-key: AKIAV73Y5N6YGKWOCB76
      secret-key: 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
    region:
      static: sa-east-1
    stack:
      auto: false

application:
  bucket:
    name: barganhaeleilao


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090